version: "3"
services:
  mongo:
    image: mongo:5.0.2
    ports:
      - "127.0.0.1:27017:27017"
    command: [ --replSet, rs0 ]
    volumes:
      - mongodb_data:/data/db:rw
      - ./conf/mongodb/01-replica-set.init.js:/docker-entrypoint-initdb.d/01-replica-set.init.js
      - ./conf/mongodb/02-collections.init.js:/docker-entrypoint-initdb.d/02-collections.init.js
    networks:
      - articles

  mailhog:
    image: mailhog/mailhog:v1.0.0
    networks:
      articles:
        aliases:
          - mailbox.example.com

  mariadb:
    image: mariadb:10.2.6
    environment:
      MYSQL_ROOT_PASSWORD: ingFXT9c8a4ESe01
    volumes:
      - mariadb_data:/var/lib/mysql/
      - ./conf/mariadb/01-privileges.init.sql:/docker-entrypoint-initdb.d/01-privileges.init.sql:ro
      - ./conf/mariadb/02-kc_primary.init.sql:/docker-entrypoint-initdb.d/02-kc_primary.init.sql:ro
    networks:
      - articles

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ingFXT9c8a4ESe01
    depends_on:
      - mariadb
    networks:
      - articles

  keycloak:
    image: jboss/keycloak:15.0.2
    command:
      - -b
      - 0.0.0.0
      - --server-config
      - standalone-ha.xml
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_PORT: 3306
      DB_DATABASE: kc_primary
      DB_USER: kc_primary_admin
      DB_PASSWORD: yBsDABFDIas5jerb
      KEYCLOAK_LOGLEVEL: DEBUG
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - keycloak_data:/data/
    depends_on:
      - mariadb
      - mailhog
    networks:
      - articles

  traefik:
    image: traefik:2.4.5
    volumes:
      - ./conf/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
    ports:
      - "127.0.0.1:80:80"
    networks:
      articles:
        aliases:
          - sso.example.com

volumes:
  mongodb_data:
  mariadb_data:
  keycloak_data:

networks:
  articles:
