version: "3"
services:
  mongo:
    image: mongo:5.0.2
    ports:
      - "127.0.0.1:27017:27017"
    command: [ --replSet, rs0 ]
    volumes:
      - mongodb_data:/data/db:rw
      - ./conf/mongodb/01-replica-set.init.js:/docker-entrypoint-initdb.d/01-replica-set.init.js
      - ./conf/mongodb/02-collections.init.js:/docker-entrypoint-initdb.d/02-collections.init.js
    networks:
      - articles

  mailhog:
    image: mailhog/mailhog:v1.0.0
    networks:
      articles:
        aliases:
          - mailbox.example.com

  mariadb:
    image: mariadb:10.2.6
    environment:
      MYSQL_ROOT_PASSWORD: ingFXT9c8a4ESe01
    volumes:
      - mariadb_data:/var/lib/mysql/
      - ./conf/mariadb/01-privileges.init.sql:/docker-entrypoint-initdb.d/01-privileges.init.sql:ro
      - ./conf/mariadb/02-kc_primary.init.sql:/docker-entrypoint-initdb.d/02-kc_primary.init.sql:ro
    networks:
      - articles

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ingFXT9c8a4ESe01
    depends_on:
      - mariadb
    networks:
      - articles

  keycloak:
    image: jboss/keycloak:15.0.2
    command:
      - -b
      - 0.0.0.0
      - --server-config
      - standalone-ha.xml
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_PORT: 3306
      DB_DATABASE: kc_primary
      DB_USER: kc_primary_admin
      DB_PASSWORD: yBsDABFDIas5jerb
      KEYCLOAK_LOGLEVEL: DEBUG
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - keycloak_data:/data/
    depends_on:
      - mariadb
      - mailhog
    networks:
      - articles

  gateway-1st:
    image: traefik:2.4.5
    volumes:
      - ./conf/traefik/gateway-1st.toml:/etc/traefik/traefik.toml:ro
    ports:
      - "127.0.0.1:80:80"
    networks:
      articles:
        aliases:
          - sso.example.com

  gatekeeper-shire:
    image: quay.io/gogatekeeper/gatekeeper:1.3.5
    expose:
      - 8080
    command:
      - --client-id=articles-webapp
      - --client-secret=268b08c4-ae72-47ae-8cbb-c0f00f2e6691
      - --discovery-url=http://sso.example.com/auth/realms/shire
      - --encryption-key=kaT0iWJO8HXfscM0HdE2izOsp8kQfYhJ
      - --enable-refresh-tokens=true
      - --secure-cookie=false
      - --listen=:8080
      - --upstream-url=http://gateway-2nd:8080
      - --upstream-response-header-timeout=30s
      - --resources=uri=/*
      - --headers=X-Auth-Realm=shire
      - --enable-authorization-header=false
      - --enable-authorization-cookies=false
      - --enable-token-header=false
      - --skip-access-token-clientid-check
      - --skip-access-token-issuer-check
    networks:
      - articles

  gatekeeper-marvel:
    image: quay.io/gogatekeeper/gatekeeper:1.3.5
    expose:
      - 8080
    command:
      - --client-id=articles-webapp
      - --client-secret=67487ed3-1dec-4698-a84f-63bf28e8f9f1
      - --discovery-url=http://sso.example.com/auth/realms/marvel
      - --encryption-key=CXhznKiFxxMnb4xwpl8D7NcHyv7aTMNf
      - --enable-refresh-tokens=true
      - --secure-cookie=false
      - --listen=:8080
      - --upstream-url=http://gateway-2nd:8080
      - --upstream-response-header-timeout=30s
      - --resources=uri=/*
      - --headers=X-Auth-Realm=marvel
      - --enable-authorization-header=false
      - --enable-authorization-cookies=false
      - --enable-token-header=false
      - --skip-access-token-clientid-check
      - --skip-access-token-issuer-check
    networks:
      - articles

  gatekeeper-galaxy:
    image: quay.io/gogatekeeper/gatekeeper:1.3.5
    expose:
      - 8080
    command:
      - --client-id=articles-webapp
      - --client-secret=3035dff0-a8ff-449d-8f7c-34d13febcc14
      - --discovery-url=http://sso.example.com/auth/realms/galaxy
      - --encryption-key=cPr87HosONcDgumXOD8E0WmE6mueYh4Y
      - --enable-refresh-tokens=true
      - --secure-cookie=false
      - --listen=:8080
      - --upstream-url=http://gateway-2nd:8080
      - --upstream-response-header-timeout=30s
      - --resources=uri=/*
      - --headers=X-Auth-Realm=galaxy
      - --enable-authorization-header=false
      - --enable-authorization-cookies=false
      - --enable-token-header=false
      - --skip-access-token-clientid-check
      - --skip-access-token-issuer-check
    networks:
      - articles

  gateway-2nd:
    image: traefik:2.4.5
    volumes:
      - ./conf/traefik/gateway-2nd.toml:/etc/traefik/traefik.toml:ro
    networks:
      - articles

  articles-backend:
    image: articles-backend:latest
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      SPRING_DATA_MONGODB_DATABASE: articles
      ANONYMOUS_ALLOWED: "false"
      REALM_HEADER: X-Auth-Realm
      USERID_HEADER: X-Auth-Userid
      USERNAME_HEADER: X-Auth-Username
    networks:
      - articles

  articles-webapp:
    image: articles-webapp:latest
    networks:
      - articles

volumes:
  mongodb_data:
  mariadb_data:
  keycloak_data:

networks:
  articles:
